name: 24/7 Honeygain Automation

on:
  schedule:
    # This runs the script every 6 hours to ensure it stays active
    - cron: '0 */6 * * *'
  workflow_dispatch: # Allows you to start it manually

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Honeygain Docker
        run: |
          docker run -d --name honeygain \
          honeygain/honeygain -tou-accept \
          -email ${{ secrets.HONEYGAIN_EMAIL }} \
          -pass ${{ secrets.HONEYGAIN_PASS }} \
          -device "Z-ONE-GitHub-Node"

      - name: Keep Alive
        run: |
          echo "Honeygain node is running..."
          sleep 300 # Keeps the action running for 5 minutes to confirm connection
          docker ps
